name: main-ci

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  ci:
    runs-on: ubuntu-latest

    # env:
    #   AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #   AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      # checkout v2, with recursive submodule update
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      # build the Docker image we use to run the tests
      - name: test.sh
        run: ./docker-test.sh

      # See https://github.com/marketplace/actions/s3-deploy
      # - name: Deploy
      #   uses: reggionick/s3-deploy@v3
      #   with:
      #     folder: src/artifacts
      #     bucket: ${{ secrets.S3_BUCKET }}
      #     bucket-region: ${{ secrets.S3_BUCKET_REGION }}
      #     dist-id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
      #     invalidation: /
      #     delete-removed: true
      #     no-cache: true
      #     private: true
